version: "3"

networks:
   network:
      driver: bridge

services:

   tomcat:
     container_name: tomcat
     image: tomcat
     ports:
       - "81:8080"
     volumes:
       - ./target/mds-1.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
       - ./target/mds-1.0.1-SNAPSHOT:/usr/local/tomcat/webapps/ROOT
   portainer:
     container_name: vision
     image: portainer/portainer
     ports:
       - 9001:9000
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./mount/vision/:/data portainer/portainer
     networks:
       - network

   proxy: 
     container_name: nginx
     image: nginx 
     volumes: # mount custom config at runtime 
       - ./mount/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
       - ./mount/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
         # - ./mount/nginx/conf/dev.app.conf:/etc/nginx/conf.d/default.conf  
       - ./mount/nginx/pages/:/usr/share/nginx/html/
     depends_on:
       - tomcat      
     links:
       - portainer:vision
       - tomcat:tomcat
     ports: 
       - 80:80
         #- 443:443
     networks:
       - network

